# --- OPTIMISATION BATTERIE 110mAh ---
# Activer la mise en veille profonde (Deep Sleep)
CONFIG_ZMK_SLEEP=y
# Temps avant mise en veille : 15 minutes (15 * 60 * 1000 millisecondes)
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000

# Améliore la stabilité et la puissance du signal Bluetooth
CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y

# --- ZMK STUDIO ---
# Activation de ZMK Studio pour modifier le keymap à la volée
CONFIG_ZMK_STUDIO=y
